[package]
name = "advent-of-code"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.75"
clap = { version = "4.4.10", features = ["derive"] }

[lints]
clippy.pedantic = "warn"
clippy.use_self = "warn"
